_core:
  default_config_hash: SwDzMQWH_m4gaInWZ_ioWc09pITzfAAMXNLS4dXs95U
select_registration_roles_setby_admin:
  tutor: tutor
  student: student
  content_editor: '0'
  administrator: '0'
select_registration_roles_admin_approval:
  tutor: tutor
  student: student
  content_editor: '0'
  administrator: '0'
select_registration_roles_auth_role: false
select_registration_roles_required: true
select_registration_roles_multiple: false
