on: 
  push:
    branches:
      - release
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.drupaldomain.online
        username: ${{ secrets.ftp_stage_user }}
        password: ${{ secrets.ftp_stage_password }}
        server_dir: /home/drupaldo/public_html/stage-admin